### PR TITLE
Avoid multiple meeting creation when multiple clicks on channel header or force meeting, and minor style fix.

### LINKED ISSUE #31: MS Teams collision detection will throw an error if users mashes the Create New Meeting button
For MS Teams collision detection, there is a delay of a few seconds when there is an existing meeting and the user clicks Create New Meeting

If the user mashes the button by clicking it many times during this delay it can produce an error in an ephemeral post. The user will then see one meeting creation post for each of the times they've click the button. 

I was not able to repro this on Zoom. I also don't see this same 2-3 second delay when creating a new meeting from the collision post. 

There is no issue with the Create New Meeting button if you just wait for a few seconds for your new meeting to launch. 

Steps
- Setup MS Team Calling
- Start a meeting 
- Click the connect link and map the user is needed
- Immediately start a 2nd meeting 
- When the collision post appears - Mash the `Create New Meeting` button very quickly
**Observed**: 
MSTeams-Collison

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Avoid multiple meeting creation when multiple clicks on channel header or force meeting.
Also fix icon positioning on create meeting and force meeting posts.

#### Ticket Link
Fix #31

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Comment by hanzei** [comment]
Heads up that there are some linter errors: https://app.circleci.com/pipelines/github/mattermost/mattermost-plugin-msteams-meetings/192/workflows/b2ff2906-38d3-4819-b979-64483f90ecc3/jobs/581

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Clicking the Create New Meeting button multiple times before the application has a chance do respond does nothing
- Once the application responds, It creates one meeting not 1 for each time the button was clicked
- The delay on create new also seems to have improved
- Regression tested collision functionality (Channel specific, no issues with other call providers)

LGTM!
Will re-test if code review results in further changes.

**Review by iomodo — APPROVED** [review]
👍

**Pull request merged**
