### PR TITLE
Bump version to 0.1.0

### PR DESCRIPTION
**Pull request by larkox**
### Summary
Bump version to v0.1.0

Proposal to initial release of MS Teams Meeting

### Ticket Link
https://github.com/mattermost/mattermost-plugin-msteams-meetings/issues/21

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
:rocket:

**Review by DHaussermann — APPROVED** [review]
Tested and passed
Release testing summary
- Tested authentication
- Tested meeting creation
- Tested meetings with multiple users 
- Unmapped users can still join meetings but not create
- Tested plugin icon and slash command 
- Tested using this from browser and desktop
- Tested all channel types
- Tested collision detections
- Verify last 2 fixes post-merge
- Confirmed with @aaronrothschild the version number for this will be `0.1.0`

LGTM!

Added tests for this to plugin release testing.

**Pull request merged**
