### PR TITLE
Sync with starter template and update dependencies

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Sync with starter template and update dependencies

#### Ticket Link
None

### CODE REVIEW

**Review by hanzei — COMMENTED** [review]
There are - unfortunately - a lot of conflicts. Would you please resolve them and I will give this PR a swiftly review?

**Comment by larkox** [comment]
@hanzei There seems to be some problems with CI, but not sure how to fix it. Any pointers?

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-plugin-msteams-meetings/pull/81 need to be merged first.

**Comment by hanzei** [comment]
@larkox I've merged `master` into your branch. I think the CI issues are "real" ones now.

**Comment by larkox** [comment]
@hanzei There seems to be some weird integrity (sha512) errors. Not sure how much of that has to do with my changes.

**Comment by hanzei** [comment]
@larkox While I can reproduce the exact CI issue I'm also running into issues on my local machine:

```
$make test
[...]
PASS
ok  	github.com/mattermost/mattermost-plugin-msteams-meetings/server	0.042s
cd webapp && /home/bschumacher/.nvm/versions/node/v13.14.0/bin/npm run test;

> mstmeetings@1.0.7 test /home/bschumacher/src/mattermost/plugins/msteams-meetings/webapp
> jest --forceExit --detectOpenHandles --verbose

 FAIL  src/manifest.test.tsx
  ● Test suite failed to run

    Cannot find module 'react-dom' from 'node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js'

    Require stack:
      node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js
      node_modules/enzyme-adapter-react-16/build/index.js
      node_modules/mattermost-webapp/tests/setup.js
      tests/setup.tsx

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:3:1)

 FAIL  src/manifest.test.ts
  ● Test suite failed to run

    Cannot find module 'react-dom' from 'node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js'

    Require stack:
      node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js
      node_modules/enzyme-adapter-react-16/build/index.js
      node_modules/mattermost-webapp/tests/setup.js
      tests/setup.tsx

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:3:1)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        2.879 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mstmeetings@1.0.7 test: `jest --forceExit --detectOpenHandles --verbose`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mstmeetings@1.0.7 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bschumacher/.npm/_logs/2022-12-01T19_12_35_816Z-debug.log
make: *** [Makefile:199: test] Error 1

```

```
$make check-style
Checking for style guide compliance
cd webapp && npm run lint

> mstmeetings@1.0.7 lint /home/bschumacher/src/mattermost/plugins/msteams-meetings/webapp
> eslint --ignore-pattern node_modules --ignore-pattern dist --ext .js --ext .jsx --ext tsx --ext ts . --quiet --cache

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration .
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.1.0

YOUR TYPESCRIPT VERSION: 4.7.2

Please only submit bug reports when using the officially supported version.

=============

/home/bschumacher/src/mattermost/plugins/msteams-meetings/webapp/src/components/icon.tsx
  4:8  error  'React' was used before it was defined  no-use-before-define

/home/bschumacher/src/mattermost/plugins/msteams-meetings/webapp/src/components/post_type_mstmeetings/post_type_mstmeetings.tsx
  4:8  error  'React' was used before it was defined  no-use-before-define

/home/bschumacher/src/mattermost/plugins/msteams-meetings/webapp/src/index.tsx
  4:8  error  'React' was used before it was defined  no-use-before-define

✖ 3 problems (3 errors, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mstmeetings@1.0.7 lint: `eslint --ignore-pattern node_modules --ignore-pattern dist --ext .js --ext .jsx --ext tsx --ext ts . --quiet --cache`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mstmeetings@1.0.7 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bschumacher/.npm/_logs/2022-12-01T19_13_52_562Z-debug.log
make: *** [Makefile:42: check-style] Error 1

[...]

**Comment by larkox** [comment]
I am not able to make this work on my local, so I will be closing it for now. If this PR is still useful, fell free to reopen it and keep working on top of it.

**Pull request closed without merging**
